-- Final safe fix for InCheck360 Advanced ML v3
-- Raw imported report rows are source data only. Analytics are generated by run_advanced_report_ml_v3.

alter table if exists public.ml_location_report_features
  add column if not exists source_type text not null default 'generated_analytics',
  add column if not exists generated_by text,
  add column if not exists model_version text,
  add column if not exists calculation_run_id uuid;

alter table if exists public.ai_insights
  add column if not exists source_type text not null default 'generated_analytics',
  add column if not exists generated_by text,
  add column if not exists model_version text,
  add column if not exists generation_run_id uuid,
  add column if not exists raw_source_count integer not null default 0;

alter table if exists public.audit_reports add column if not exists source_type text not null default 'raw_imported_report';
alter table if exists public.audit_report_items add column if not exists source_type text not null default 'raw_imported_report';
alter table if exists public.completion_rate_reports add column if not exists source_type text not null default 'raw_imported_report';
alter table if exists public.completion_rate_checklists add column if not exists source_type text not null default 'raw_imported_report';

create table if not exists public.analytics_generation_runs (
  calculation_run_id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(organization_id) on delete cascade,
  period_start date not null,
  period_end date not null,
  engine_name text not null default 'InCheck360 Advanced Internal ML',
  model_version text not null default 'advanced_report_ml_v3',
  status text not null default 'running' check (status in ('running', 'completed', 'failed')),
  raw_rows_scanned integer not null default 0,
  generated_feature_rows integer not null default 0,
  generated_score_rows integer not null default 0,
  generated_insight_rows integer not null default 0,
  triggered_by text,
  error_message text,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  created_at timestamptz not null default now()
);

drop view if exists public.v_analytics_data_lineage cascade;

create or replace view public.v_analytics_data_lineage as
select ar.organization_id, 'RAW IMPORTED DATA'::text as layer, 'audit_reports'::text as table_name, count(*)::bigint as row_count, 'raw_imported_report'::text as source_type, null::text as generated_by, null::text as model_version, null::uuid as calculation_run_id, max(ar.created_at) as last_activity_at, 10 as sort_order
from public.audit_reports ar group by ar.organization_id
union all
select ai.organization_id, 'RAW IMPORTED DATA', 'audit_report_items', count(*)::bigint, 'raw_imported_report', null::text, null::text, null::uuid, max(ai.created_at), 20
from public.audit_report_items ai group by ai.organization_id
union all
select cr.organization_id, 'RAW IMPORTED DATA', 'completion_rate_reports', count(*)::bigint, 'raw_imported_report', null::text, null::text, null::uuid, max(cr.created_at), 30
from public.completion_rate_reports cr group by cr.organization_id
union all
select cc.organization_id, 'RAW IMPORTED DATA', 'completion_rate_checklists', count(*)::bigint, 'raw_imported_report', null::text, null::text, null::uuid, max(cc.created_at), 40
from public.completion_rate_checklists cc group by cc.organization_id
union all
select ml.organization_id, 'GENERATED ANALYTICS', 'ml_location_report_features', count(*)::bigint, 'generated_analytics', coalesce(max(to_jsonb(ml)->>'generated_by'), 'advanced_ml_unknown'), coalesce(max(to_jsonb(ml)->>'model_version'), 'unknown'), nullif(max(to_jsonb(ml)->>'calculation_run_id'), '')::uuid, max(ml.calculated_at), 110
from public.ml_location_report_features ml group by ml.organization_id
union all
select ins.organization_id, 'GENERATED ANALYTICS', 'ai_insights', count(*)::bigint, 'generated_analytics', coalesce(max(to_jsonb(ins)->>'generated_by'), 'advanced_ml_unknown'), coalesce(max(to_jsonb(ins)->>'model_version'), 'unknown'), nullif(max(to_jsonb(ins)->>'generation_run_id'), '')::uuid, max(ins.generated_at), 130
from public.ai_insights ins group by ins.organization_id;

create or replace function public.verify_raw_vs_generated_analytics(p_organization_id uuid)
returns table (layer text, table_name text, row_count bigint, source_type text, generated_by text, model_version text, calculation_run_id uuid, last_activity_at timestamptz)
language sql stable security definer set search_path = public as $$
  select v.layer, v.table_name, v.row_count, v.source_type, v.generated_by, v.model_version, v.calculation_run_id, v.last_activity_at
  from public.v_analytics_data_lineage v
  where v.organization_id = p_organization_id
  order by v.sort_order;
$$;

create or replace function public.run_advanced_report_ml_v3(
  p_organization_id uuid,
  p_period_start date,
  p_period_end date,
  p_triggered_by text default 'manual'
)
returns table (calculation_run_id uuid, organization_id uuid, period_start date, period_end date, raw_rows_scanned integer, generated_feature_rows integer, generated_score_rows integer, generated_insight_rows integer, status text)
language plpgsql security definer set search_path = public as $$
declare
  v_calc_run_id uuid;
  v_started_at timestamptz := now();
  v_raw_count integer := 0;
  v_feature_count integer := 0;
  v_insight_count integer := 0;
begin
  select (
    (select count(*) from public.audit_reports ar where ar.organization_id = p_organization_id and coalesce(ar.report_date, ar.completed_at::date, ar.created_at::date) between p_period_start and p_period_end) +
    (select count(*) from public.audit_report_items ai where ai.organization_id = p_organization_id and coalesce(ai.completed_at::date, ai.created_at::date) between p_period_start and p_period_end) +
    (select count(*) from public.completion_rate_reports cr where cr.organization_id = p_organization_id and coalesce(cr.date_range_end, cr.date_range_start, cr.created_at::date) between p_period_start and p_period_end) +
    (select count(*) from public.completion_rate_checklists cc where cc.organization_id = p_organization_id)
  )::integer into v_raw_count;

  insert into public.analytics_generation_runs (organization_id, period_start, period_end, status, raw_rows_scanned, triggered_by, started_at)
  values (p_organization_id, p_period_start, p_period_end, 'running', v_raw_count, p_triggered_by, v_started_at)
  returning analytics_generation_runs.calculation_run_id into v_calc_run_id;

  delete from public.ai_insights ins
  where ins.organization_id = p_organization_id and coalesce(to_jsonb(ins)->>'generated_by', '') in ('advanced_ml_v3', 'advanced_report_ml_v3', 'advanced_ml_v2');

  delete from public.ml_location_report_features ml
  where ml.organization_id = p_organization_id and ml.period_start = p_period_start and ml.period_end = p_period_end;

  if to_regprocedure('public.run_advanced_report_ml_v2(uuid,date,date)') is not null then
    perform public.run_advanced_report_ml_v2(p_organization_id, p_period_start, p_period_end);
  elsif to_regprocedure('public.run_advanced_report_ml(uuid,date,date)') is not null then
    perform public.run_advanced_report_ml(p_organization_id, p_period_start, p_period_end);
  elsif to_regprocedure('public.run_internal_ml_from_imported_reports(uuid,date,date)') is not null then
    perform public.run_internal_ml_from_imported_reports(p_organization_id, p_period_start, p_period_end);
  else
    raise exception 'No report ML function is installed. Run advanced_report_ml_analytics_upgrade.sql first.';
  end if;

  update public.ml_location_report_features ml
  set source_type = 'generated_analytics', generated_by = 'advanced_ml_v3', model_version = 'advanced_report_ml_v3', calculation_run_id = v_calc_run_id
  where ml.organization_id = p_organization_id and ml.period_start = p_period_start and ml.period_end = p_period_end;

  update public.ai_insights ins
  set source_type = 'generated_analytics', generated_by = 'advanced_ml_v3', model_version = 'advanced_report_ml_v3', generation_run_id = v_calc_run_id, raw_source_count = v_raw_count
  where ins.organization_id = p_organization_id and ins.generated_at >= v_started_at;

  select count(*)::integer into v_feature_count
  from public.ml_location_report_features ml
  where ml.organization_id = p_organization_id and ml.calculation_run_id = v_calc_run_id;

  select count(*)::integer into v_insight_count
  from public.ai_insights ins
  where ins.organization_id = p_organization_id and nullif(to_jsonb(ins)->>'generation_run_id', '')::uuid = v_calc_run_id;

  update public.analytics_generation_runs agr
  set status = 'completed', generated_feature_rows = v_feature_count, generated_score_rows = 0, generated_insight_rows = v_insight_count, finished_at = now()
  where agr.calculation_run_id = v_calc_run_id;

  return query select v_calc_run_id, p_organization_id, p_period_start, p_period_end, v_raw_count, v_feature_count, 0, v_insight_count, 'completed'::text;
exception when others then
  if v_calc_run_id is not null then
    update public.analytics_generation_runs agr set status = 'failed', error_message = sqlerrm, finished_at = now() where agr.calculation_run_id = v_calc_run_id;
  end if;
  raise;
end;
$$;

grant select on public.analytics_generation_runs to anon, authenticated;
grant select on public.v_analytics_data_lineage to anon, authenticated;
grant execute on function public.verify_raw_vs_generated_analytics(uuid) to anon, authenticated;
grant execute on function public.run_advanced_report_ml_v3(uuid, date, date, text) to anon, authenticated;

select 'final_safe_ml_v3_fix_installed' as status;
