-- InCheck360 Advanced ML v3 Clean Lineage
-- Raw imported report rows are source data only. Analytics are generated by run_advanced_report_ml_v3.
-- Fix: PostgreSQL has no max(uuid), so lineage UUID aggregation casts uuid -> text -> uuid.

begin;

alter table public.ml_location_report_features
  add column if not exists source_type text not null default 'generated_analytics',
  add column if not exists generated_by text,
  add column if not exists model_version text,
  add column if not exists calculation_run_id uuid;

alter table public.internal_ml_location_scores
  add column if not exists source_type text not null default 'generated_analytics',
  add column if not exists generated_by text,
  add column if not exists model_version text,
  add column if not exists generation_run_id uuid;

alter table public.ai_insights
  add column if not exists source_type text not null default 'generated_analytics',
  add column if not exists generated_by text,
  add column if not exists model_version text,
  add column if not exists generation_run_id uuid,
  add column if not exists raw_source_count integer not null default 0;

alter table public.audit_reports add column if not exists source_type text not null default 'raw_imported_report';
alter table public.audit_report_items add column if not exists source_type text not null default 'raw_imported_report';
alter table public.completion_rate_reports add column if not exists source_type text not null default 'raw_imported_report';
alter table public.completion_rate_checklists add column if not exists source_type text not null default 'raw_imported_report';

create table if not exists public.analytics_generation_runs (
  calculation_run_id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(organization_id) on delete cascade,
  period_start date not null,
  period_end date not null,
  engine_name text not null default 'InCheck360 Advanced Internal ML',
  model_version text not null default 'advanced_report_ml_v3',
  status text not null default 'running' check (status in ('running', 'completed', 'failed')),
  raw_rows_scanned integer not null default 0,
  generated_feature_rows integer not null default 0,
  generated_score_rows integer not null default 0,
  generated_insight_rows integer not null default 0,
  triggered_by text,
  error_message text,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  created_at timestamptz not null default now()
);

create or replace view public.v_analytics_data_lineage as
select organization_id, 'RAW IMPORTED DATA'::text layer, 'audit_reports'::text table_name, count(*)::bigint row_count, 'raw_imported_report'::text source_type, null::text generated_by, null::text model_version, null::uuid calculation_run_id, max(created_at) last_activity_at, 10 sort_order from public.audit_reports group by organization_id
union all select organization_id, 'RAW IMPORTED DATA', 'audit_report_items', count(*)::bigint, 'raw_imported_report', null::text, null::text, null::uuid, max(created_at), 20 from public.audit_report_items group by organization_id
union all select organization_id, 'RAW IMPORTED DATA', 'completion_rate_reports', count(*)::bigint, 'raw_imported_report', null::text, null::text, null::uuid, max(created_at), 30 from public.completion_rate_reports group by organization_id
union all select organization_id, 'RAW IMPORTED DATA', 'completion_rate_checklists', count(*)::bigint, 'raw_imported_report', null::text, null::text, null::uuid, max(created_at), 40 from public.completion_rate_checklists group by organization_id
union all select organization_id, 'GENERATED ANALYTICS', 'ml_location_report_features', count(*)::bigint, 'generated_analytics', coalesce(max(generated_by), 'advanced_ml_unknown'), coalesce(max(model_version), 'unknown'), max(calculation_run_id::text)::uuid, max(calculated_at), 110 from public.ml_location_report_features group by organization_id
union all select organization_id, 'GENERATED ANALYTICS', 'internal_ml_location_scores', count(*)::bigint, 'generated_analytics', coalesce(max(generated_by), 'advanced_ml_unknown'), coalesce(max(model_version), 'unknown'), max(generation_run_id::text)::uuid, max(scored_at), 120 from public.internal_ml_location_scores group by organization_id
union all select organization_id, 'GENERATED ANALYTICS', 'ai_insights', count(*)::bigint, 'generated_analytics', coalesce(max(generated_by), 'advanced_ml_unknown'), coalesce(max(model_version), 'unknown'), max(generation_run_id::text)::uuid, max(generated_at), 130 from public.ai_insights group by organization_id;

create or replace function public.run_advanced_report_ml_v3(
  p_organization_id uuid,
  p_period_start date,
  p_period_end date,
  p_triggered_by text default 'manual'
)
returns table (
  calculation_run_id uuid,
  organization_id uuid,
  period_start date,
  period_end date,
  raw_rows_scanned integer,
  generated_feature_rows integer,
  generated_score_rows integer,
  generated_insight_rows integer,
  status text
)
language plpgsql security definer set search_path = public as $$
declare
  v_calc_run_id uuid;
  v_started_at timestamptz := now();
  v_raw_count integer := 0;
  v_feature_count integer := 0;
  v_score_count integer := 0;
  v_insight_count integer := 0;
begin
  select (
    (select count(*) from public.audit_reports where organization_id = p_organization_id and coalesce(report_date, completed_at::date, created_at::date) between p_period_start and p_period_end) +
    (select count(*) from public.audit_report_items where organization_id = p_organization_id and coalesce(completed_at::date, created_at::date) between p_period_start and p_period_end) +
    (select count(*) from public.completion_rate_reports where organization_id = p_organization_id and coalesce(date_range_end, date_range_start, created_at::date) between p_period_start and p_period_end) +
    (select count(*) from public.completion_rate_checklists where organization_id = p_organization_id)
  )::integer into v_raw_count;

  insert into public.analytics_generation_runs (organization_id, period_start, period_end, status, raw_rows_scanned, triggered_by, started_at)
  values (p_organization_id, p_period_start, p_period_end, 'running', v_raw_count, p_triggered_by, v_started_at)
  returning analytics_generation_runs.calculation_run_id into v_calc_run_id;

  delete from public.ai_insights where organization_id = p_organization_id and coalesce(generated_by, '') in ('advanced_ml_v3', 'advanced_report_ml_v3', 'advanced_ml_v2');
  delete from public.internal_ml_location_scores where organization_id = p_organization_id and coalesce(generated_by, '') in ('advanced_ml_v3', 'advanced_report_ml_v3', 'advanced_ml_v2');
  delete from public.ml_location_report_features where organization_id = p_organization_id and period_start = p_period_start and period_end = p_period_end;

  perform public.run_advanced_report_ml_v2(p_organization_id, p_period_start, p_period_end);

  update public.ml_location_report_features set source_type = 'generated_analytics', generated_by = 'advanced_ml_v3', model_version = 'advanced_report_ml_v3', calculation_run_id = v_calc_run_id
  where organization_id = p_organization_id and period_start = p_period_start and period_end = p_period_end;

  update public.internal_ml_location_scores set source_type = 'generated_analytics', generated_by = 'advanced_ml_v3', model_version = 'advanced_report_ml_v3', generation_run_id = v_calc_run_id
  where organization_id = p_organization_id and scored_at >= v_started_at;

  update public.ai_insights set source_type = 'generated_analytics', generated_by = 'advanced_ml_v3', model_version = 'advanced_report_ml_v3', generation_run_id = v_calc_run_id, raw_source_count = v_raw_count
  where organization_id = p_organization_id and generated_at >= v_started_at;

  select count(*)::integer into v_feature_count from public.ml_location_report_features where organization_id = p_organization_id and calculation_run_id = v_calc_run_id;
  select count(*)::integer into v_score_count from public.internal_ml_location_scores where organization_id = p_organization_id and generation_run_id = v_calc_run_id;
  select count(*)::integer into v_insight_count from public.ai_insights where organization_id = p_organization_id and generation_run_id = v_calc_run_id;

  update public.analytics_generation_runs set status = 'completed', generated_feature_rows = v_feature_count, generated_score_rows = v_score_count, generated_insight_rows = v_insight_count, finished_at = now()
  where analytics_generation_runs.calculation_run_id = v_calc_run_id;

  return query select v_calc_run_id, p_organization_id, p_period_start, p_period_end, v_raw_count, v_feature_count, v_score_count, v_insight_count, 'completed'::text;
exception when others then
  update public.analytics_generation_runs set status = 'failed', error_message = sqlerrm, finished_at = now() where analytics_generation_runs.calculation_run_id = v_calc_run_id;
  raise;
end;
$$;

create or replace function public.verify_raw_vs_generated_analytics(p_organization_id uuid)
returns table (layer text, table_name text, row_count bigint, source_type text, generated_by text, model_version text, calculation_run_id uuid, last_activity_at timestamptz)
language sql stable security definer set search_path = public as $$
  select layer, table_name, row_count, source_type, generated_by, model_version, calculation_run_id, last_activity_at
  from public.v_analytics_data_lineage
  where organization_id = p_organization_id
  order by sort_order;
$$;

grant select on public.analytics_generation_runs to anon, authenticated;
grant select on public.v_analytics_data_lineage to anon, authenticated;
grant execute on function public.run_advanced_report_ml_v3(uuid, date, date, text) to anon, authenticated;
grant execute on function public.verify_raw_vs_generated_analytics(uuid) to anon, authenticated;

commit;
